version: '3'

services:
    app:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: app
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        env_file:
            - .env
        depends_on:
            - postgresql
        networks:
            - laravel_network

    postgresql:
        image: postgres:13
        container_name: postgresql
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: postgresql
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
            - ./docker/postgresql/my.cnf:/etc/postgresql/conf.d/my.cnf
        networks:
            - laravel_network

volumes:
    my-laravel-postgresql:

networks:
    laravel_network:
        driver: bridge
